### ISSUE TITLE
Can not install seisbench from source files

### ISSUE THREAD

**Issue by JUNZHU-SEIS** [seisbench/seisbench#175]
Branch: phasenet-fix
```
pip install .
```
Error output

Maybe due to no packages defined in [requirements.txt](https://github.com/seisbench/seisbench/blob/phasenet_fix/requirements.txt)

**Comment by yetinam** [comment]
Hi @JUNZHU-SEIS ,
I need more information on the issue. Can you please paste the error output? Can you also provide your operating system and python version. The empty requirements.txt should not cause issues as dependencies are defined in the pyproject.toml

**Comment by JUNZHU-SEIS** [comment]
Output:
```
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing /storage/lilab/jzhu/Work/Mariana/transfer_learning/seisbench-phasenet_fix
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      Traceback (most recent call last):
        File "/home/lilab/jzhu/data/anaconda3/envs/OBS/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/home/lilab/jzhu/data/anaconda3/envs/OBS/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/lilab/jzhu/data/anaconda3/envs/OBS/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-i89ajd5k/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-i89ajd5k/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-i89ajd5k/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 3, in <module>
        File "/tmp/pip-build-env-i89ajd5k/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-i89ajd5k/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
                                       ^^^^^^^^^^^^
        File "/tmp/pip-build-env-i89ajd5k/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 488, in __init__
          _Distribution.__init__(
        File "/tmp/pip-build-env-i89ajd5k/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
          self.finalize_options()
        File "/tmp/pip-build-env-i89ajd5k/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 912, in finalize_options
          ep(self)
        File "/tmp/pip-build-env-i89ajd5k/overlay/lib/python3.11/site-packages/setuptools_scm/integration.py", line 127, in infer_version
          _assign_version(dist, config)
        File "/tmp/pip-build-env-i89ajd5k/overlay/lib/python3.11/site-packages/setuptools_scm/integration.py", line 63, in _assign_version
          _version_missing(config)
        File "/tmp/pip-build-env-i89ajd5k/overlay/lib/python3.11/site-packages/setuptools_scm/__init__.py", line 108, in _version_missing
          raise LookupError(
      LookupError: setuptools-scm was unable to detect version for /storage/lilab/jzhu/Work/Mariana/transfer_learning/seisbench-phasenet_fix.
      
      Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
      
      For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
System: 
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
```
Python:
```
Python 3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:24:40) [GCC 10.4.0] on linux
```

**Comment by yetinam** [comment]
Thanks for updating this. Which way did you obtain the source code?
Could the lookup error detailed in your stack trace be the problem?
```
LookupError: setuptools-scm was unable to detect version for /storage/lilab/jzhu/Work/Mariana/transfer_learning/seisbench-phasenet_fix.
      
      Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
      
      For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
      [end of output]
```

In addition, we're not testing on python 3.11 yet, as pytorch is not supported on all distributions in python 3.11. On Ubuntu I think you should be fine though.

**Comment by JUNZHU-SEIS** [comment]
Thanks for your reply. Maybe it's because of lookup error. I obtained the source code by
```
wget https://github.com/seisbench/seisbench/archive/refs/heads/phasenet_fix.zip
```
I have changed Python to v3.7 but got the same error output.
But if I run the same code for the old package (the reuquirements.txt file is NOT empty), everything is OK.

**Comment by yetinam** [comment]
Hi @JUNZHU-SEIS , this is related to the changes in #163. We now use setuptools-scm for version inference. This requires the existence of a .git folder locally. To solve this, please follow the instructions in the error trace or obtain the source code directly through `git clone`.
