### ISSUE TITLE
ConnectionError

### ISSUE THREAD

**Issue by ibralsalmi** [seisbench/seisbench#228]
I am trying to load  pre-trained PhaseNet model as following code: 

import seisbench
import seisbench.models as sbm

# Load in pre-trained PhaseNet model
pn_model = sbm.PhaseNet.from_pretrained("stead")

I face bellow issue, I think it is related to VPN required problem, happened because firewall, 
 
2023-08-13 16:11:33,461 | seisbench | WARNING | The download precheck failed with a connection error. This is not an error itself, but might indicate a subsequent error. If you encounter an error, this might be caused by the firewall setup of your network. Please check https://github.com/seisbench/seisbench#known-issues for details.
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\seisB\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "C:\ProgramData\anaconda3\envs\seisB\lib\site-packages\urllib3\connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "C:\ProgramData\anaconda3\envs\seisB\lib\site-packages\urllib3\connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "C:\ProgramData\anaconda3\envs\seisB\lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "C:\ProgramData\anaconda3\envs\seisB\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\ProgramData\anaconda3\envs\seisB\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\ProgramData\anaconda3\envs\seisB\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\ProgramData\anaconda3\envs\seisB\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "C:\ProgramData\anaconda3\envs\seisB\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\seisB\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\ProgramData\anaconda3\envs\seisB\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "C:\ProgramData\anaconda3\envs\seisB\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\ProgramData\anaconda3\envs\seisB\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "C:\ProgramData\anaconda3\envs\seisB\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "C:\ProgramData\anaconda3\envs\seisB\lib\site-packages\urllib3\connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "C:\ProgramData\anaconda3\envs\seisB\lib\site-packages\urllib3\connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "C:\ProgramData\anaconda3\envs\seisB\lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "C:\ProgramData\anaconda3\envs\seisB\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\ProgramData\anaconda3\envs\seisB\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\ProgramData\anaconda3\envs\seisB\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\ProgramData\anaconda3\envs\seisB\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "C:\ProgramData\anaconda3\envs\seisB\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\trimSeed\seisB\7.py", line 19, in <module>
    pn_model = sbm.PhaseNet.from_pretrained("stead")
  File "C:\ProgramData\anaconda3\envs\seisB\lib\site-packages\seisbench\models\base.py", line 209, in from_pretrained
    versions = cls.list_versions(name, remote=True)
  File "C:\ProgramData\anaconda3\envs\seisB\lib\site-packages\seisbench\models\base.py", line 462, in list_versions
    files = seisbench.util.ls_webdav(remote_path)
  File "C:\ProgramData\anaconda3\envs\seisB\lib\site-packages\seisbench\util\file.py", line 168, in ls_webdav
    ret = sess.send(prep)
  File "C:\ProgramData\anaconda3\envs\seisB\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\ProgramData\anaconda3\envs\seisB\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

I am try  to use a pretrained model called ethz as following:

import seisbench
import seisbench.models as sbm

import seisbench
from urllib.parse import urljoin

seisbench.remote_root = "https://hifis-storage.desy.de:2880/Helmholtz/HelmholtzAI/SeisBench/"
seisbench.remote_data_root = urljoin(seisbench.remote_root, "datasets/")
seisbench.remote_model_root = urljoin(seisbench.remote_root, "models/v3/")
# Various pre-trained weights for PhaseNet
pn_model = sbm.PhaseNet.from_pretrained("ethz")
pn_model.cpu()

I face the below issue:

2023-08-07 17:46:53,547 | seisbench | WARNING | The download precheck failed with status code 500. This is not an error itself, but might indicate a subsequent error. If you encounter an error, this might be caused by the firewall setup of your network. Please check https://github.com/seisbench/seisbench#known-issues for details.
Traceback (most recent call last):
  File "6.py", line 31, in <module>
    pn_model = sbm.PhaseNet.from_pretrained("ethz")
  File "C:\Users\Ibralsalmi\anaconda3\envs\ml\lib\site-packages\seisbench\models\base.py", line 209, in from_pretrained
    versions = cls.list_versions(name, remote=True)
  File "C:\Users\Ibralsalmi\anaconda3\envs\ml\lib\site-packages\seisbench\models\base.py", line 462, in list_versions
    files = seisbench.util.ls_webdav(remote_path)
  File "C:\Users\Ibralsalmi\anaconda3\envs\ml\lib\site-packages\seisbench\util\file.py", line 172, in ls_webdav
    f"Invalid URL. Request returned status code {ret.status_code}."
ValueError: Invalid URL. Request returned status code 500.

What should I do? I can't install from https://hifis-storage.desy.de:2880/Helmholtz/HelmholtzAI/SeisBench/ and any VPN software required?

**Comment by yetinam** [comment]
Hi, thanks for the detailed report. I think this is not an issue on your side but with our servers, probably related to #224 . As a workaround until a definitive fix, you can get the model weights this way: https://github.com/seisbench/seisbench/issues/206#issuecomment-1591002290 .

**Comment by ibralsalmi** [comment]
Hi, thanks for help, so I will load like bellow:

import torch
import seisbench.models as sbm

# Copy the model architecture
model = sbm.PhaseNet()
# Load the now locally stored weights in
model.load_state_dict(torch.load('X.pt'))# X name of file

**Comment by yetinam** [comment]
That would only load the weights but not the configuration. Just put the files in the `~/.seisbench` directory as described and then use the `from_pretrained` function as before. As locally cached weights are now available, this will not query the online repository anymore.

**Comment by ibralsalmi** [comment]
it worked, thanks.

**Comment by ibralsalmi** [comment]
What about the Benchmark Dataset, I faced same problem, However I downloaded STEAD ( merged.csv and merged.hdf5 ~95GB), How to load in  SeisBench? I tried but not worked.

**Comment by ibralsalmi** [comment]
I faced the bellow issue:

2023-08-13 19:22:41,425 | seisbench | WARNING | No data_format group found in .hdf5 File.
2023-08-13 19:22:41,425 | seisbench | WARNING | Dimension order not specified in data set. Assuming CW.
2023-08-13 19:22:41,425 | seisbench | WARNING | Sampling rate not specified in data set.
2023-08-13 19:22:41,433 | seisbench | WARNING | Component order not specified in data set. Keeping original components.
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\ml\lib\site-packages\pandas\core\indexes\base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'trace_component_order'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\trimSeed\seisB\stead\3.py", line 19, in <module>
    data = sbd.WaveformDataset(base_path, sampling_rate=100)
  File "C:\ProgramData\anaconda3\envs\ml\lib\site-packages\seisbench\data\base.py", line 163, in __init__
    self.missing_components = missing_components
  File "C:\ProgramData\anaconda3\envs\ml\lib\site-packages\seisbench\data\base.py", line 300, in missing_components
    self.component_order = (
  File "C:\ProgramData\anaconda3\envs\ml\lib\site-packages\seisbench\data\base.py", line 320, in component_order
    for source_order in self.metadata["trace_component_order"].unique():
  File "C:\ProgramData\anaconda3\envs\ml\lib\site-packages\pandas\core\frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\ProgramData\anaconda3\envs\ml\lib\site-packages\pandas\core\indexes\base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'trace_component_order'

**Comment by yetinam** [comment]
If I understood you correctly, you've downloaded the original version of STEAD? In that case, you have to transcode it to SeisBench. To do this, just use:
```
sbd.STEAD(download_kwargs={"base_path": "path/to/your/stead/files"}
```
Unfortunately, due to their size, we can't make the converted datasets available on another repository yet, so they'll only directly become available again once the repository works again.

PS: I've taken the liberty to reformat your last post. In general, it makes reading a bit easier to format error traces or code blocks this way.

**Comment by ibralsalmi** [comment]
I downloaded from here:
https://github.com/smousavi05/STEAD

Can you rewrite for me again:
data=sbd.STEAD(download_kwargs={"base_path": "C:\Users\Administrator\Desktop\trimSeed\seisB\stead"})

does not work?
I want to load it into SeisBench.

**Comment by yetinam** [comment]
Can you try just rerunning
```
import seisbench.data as sbd
data = sbd.STEAD()
```
Our server should be back up, so it should download the already converted dataset.

**Comment by ibralsalmi** [comment]
Hello
I still  facing  an issue:

2023-08-14 19:28:31,640 | seisbench | WARNING | Dataset STEAD not in cache.
2023-08-14 19:28:31,640 | seisbench | WARNING | Trying to download preprocessed version from SeisBench repository.
2023-08-14 19:28:37,171 | seisbench | WARNING | The download precheck failed with status code 404. This is not an error itself, but might indicate a subsequent error. If you encounter an error, this might be caused by the firewall setup of your network. Please check https://github.com/seisbench/seisbench#known-issues for details.
2023-08-14 19:28:42,905 | seisbench | WARNING | Dataset STEAD not in SeisBench repository. Starting download and conversion from source.
2023-08-14 19:28:42,905 | seisbench | ERROR | Error in downloading dataset. Saved current progress to C:\Users\Al-Salmi\.seisbench\datasets\stead\metadata.csv.partial and C:\Users\Al-Salmi\.seisbench\datasets\stead\waveforms.hdf5.partial. Error message:

Traceback (most recent call last):
  File "C:\Users\Al-Salmi\Desktop\10.py", line 12, in <module>
    data= sbd.STEAD()
  File "C:\Users\Al-Salmi\.conda\envs\seisB\lib\site-packages\seisbench\data\stead.py", line 27, in __init__
    super().__init__(
  File "C:\Users\Al-Salmi\.conda\envs\seisB\lib\site-packages\seisbench\data\base.py", line 2173, in __init__
    seisbench.util.callback_if_uncached(
  File "C:\Users\Al-Salmi\.conda\envs\seisB\lib\site-packages\seisbench\util\file.py", line 259, in callback_if_uncached
    callback(partial_files)
  File "C:\Users\Al-Salmi\.conda\envs\seisB\lib\site-packages\seisbench\data\base.py", line 2167, in download_callback
    self._download_dataset(writer, **tmp_download_args)
  File "C:\Users\Al-Salmi\.conda\envs\seisB\lib\site-packages\seisbench\data\stead.py", line 78, in _download_dataset
    raise ValueError(
ValueError: No cached version of STEAD found. Please download STEAD following the instructions at https://github.com/smousavi05/STEAD. Provide the locations of the STEAD unpacked files (merged.csv and merged.hdf5) in the download_kwargs argument 'basepath'.This step is only necessary the first time STEAD is loaded.

**Comment by yetinam** [comment]
This looks to me like your network is blocking the access to our server. I double-checked and it's running in Google Colab. Could you check if you can access (https://hifis-storage.desy.de:2880/Helmholtz/HelmholtzAI/SeisBench/) from your browser? If not, please reach out to your departments network administration to ask them to allow access to port 2880 on the machine.

Closing this issue now as the problem seems related to local network.
