### ISSUE TITLE
Resons of Huge memory overhead

### ISSUE THREAD

**Issue by Dong6Jx** [seisbench/seisbench#254]
Hi,
I train the model on the GPU. My data loading statement is:data = sbd.WaveformDataset(dataset_path, sampling_rate=50, cache='trace'). The training process causes huge memory overhead. What are the possible reasons? batch_size=256, is it too large?

**Comment by yetinam** [comment]
Hi!
I assume you're speaking of CPU memory? The key is in the `cache` parameter. With this setting, the whole dataset will be kept in memory once it has been iterated over once (or if you call `preload_waveforms`). Does that explain the memory usage?

**Comment by Pengling2022** [comment]
Hi, @yetinam 
I had the same problem, I ran with 03b modification in seisibench, no cache errors were encountered and the run time only took 20 minutes per epoch, but in pick-benchmark the model failed to train after I used preload_waveforms Direct MemoryError if I comment After removing preload_waveforms, I can run it, but the running time is very long (about 4 hours) and memory errors will still appear after a while. How much memory allocation do I need to avoid errors, or is there any other solution? Such as batch preload_waveforms?

**Comment by yetinam** [comment]
Hi @Pengling2022 ,

the amount of memory you need depends on the size of the dataset. A good estimate is usually the size of the file on disk. Some (but not all) datasets also give you a warning indicating the dataset size. If you do not have this amount of memory available, the only option is loading the waveforms from disk when needed. However, make sure that the `cache` parameter of the dataset is set to a value that does not implicitly cache the data.

Regarding batched loading, the pytorch DataLoader will take care of this. However, it will not make use of the block structure of the data to optimize sequential reads. This functionality is currently not implemented. In principle, you could however add such a wrapper around the `WaveformDataset` class.

**Comment by Pengling2022** [comment]
Hi， @yetinam 
I am trying to use STEAD to retrain EQTransformer. I used to directly use the Seisbench package for training. I modified the example of 03b and used the sample custom loss, etc. instead of the PL package. Now I need to store running parameters, etc., so I switched to pick. -benchmark, but I got an out of memory error. The following is the error that occurred when I unchecked train_data.preload_waveforms(pbar=True) ，：
C:\Users\hijl\.conda\envs\seisbench\python.exe D:\Study\pick-benchmark-main\pick-benchmark-main\benchmark\train.py 
WARNING:root:Overwriting learning rate to 0.001
C:\Users\hijl\.conda\envs\seisbench\lib\site-packages\pytorch_lightning\trainer\connectors\accelerator_connector.py:478: LightningDeprecationWarning: Setting `Trainer(gpus=1)` is deprecated in v1.7 and will be removed in v2.0. Please use `Trainer(accelerator='gpu', devices=1)` instead.
  rank_zero_deprecation(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA GeForce RTX 3060') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name  | Type          | Params
----------------------------------------
0 | loss  | BCELoss       | 0     
1 | model | EQTransformer | 572 K 
----------------------------------------
572 K     Trainable params
0         Non-trainable params
572 K     Total params
2.289     Total estimated model params size (MB)
Epoch 0:  65%|██████▍   | 23042/35597 [2:09:07<1:10:21,  2.97it/s, loss=0.0265, v_num=8_7]Traceback (most recent call last):
  File "D:\Study\pick-benchmark-main\pick-benchmark-main\benchmark\train.py", line 249, in <module>
    train(config, experiment_name, test_run=test_run)
  File "D:\Study\pick-benchmark-main\pick-benchmark-main\benchmark\train.py", line 86, in train
    trainer.fit(model, train_loader, dev_loader)
  File "C:\Users\hijl\.conda\envs\seisbench\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "C:\Users\hijl\.conda\envs\seisbench\lib\site-packages\pytorch_lightning\trainer\call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "C:\Users\hijl\.conda\envs\seisbench\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "C:\Users\hijl\.conda\envs\seisbench\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1112, in _run
    results = self._run_stage()
  File "C:\Users\hijl\.conda\envs\seisbench\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1191, in _run_stage
    self._run_train()
  File "C:\Users\hijl\.conda\envs\seisbench\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1214, in _run_train
    self.fit_loop.run()
  File "C:\Users\hijl\.conda\envs\seisbench\lib\site-packages\pytorch_lightning\loops\loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "C:\Users\hijl\.conda\envs\seisbench\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "C:\Users\hijl\.conda\envs\seisbench\lib\site-packages\pytorch_lightning\loops\loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "C:\Users\hijl\.conda\envs\seisbench\lib\site-packages\pytorch_lightning\loops\epoch\training_epoch_loop.py", line 187, in advance
    batch = next(data_fetcher)
  File "C:\Users\hijl\.conda\envs\seisbench\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 184, in __next__
    return self.fetching_function()
  File "C:\Users\hijl\.conda\envs\seisbench\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 265, in fetching_function
    self._fetch_next_batch(self.dataloader_iter)
  File "C:\Users\hijl\.conda\envs\seisbench\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 280, in _fetch_next_batch
    batch = next(iterator)
  File "C:\Users\hijl\.conda\envs\seisbench\lib\site-packages\pytorch_lightning\trainer\supporters.py", line 571, in __next__
    return self.request_next_batch(self.loader_iters)
  File "C:\Users\hijl\.conda\envs\seisbench\lib\site-packages\pytorch_lightning\trainer\supporters.py", line 583, in request_next_batch
    return apply_to_collection(loader_iters, Iterator, next)
  File "C:\Users\hijl\.conda\envs\seisbench\lib\site-packages\lightning_utilities\core\apply_func.py", line 64, in apply_to_collection
    return function(data, *args, **kwargs)
  File "C:\Users\hijl\.conda\envs\seisbench\lib\site-packages\torch\utils\data\dataloader.py", line 681, in __next__
    data = self._next_data()
  File "C:\Users\hijl\.conda\envs\seisbench\lib\site-packages\torch\utils\data\dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "C:\Users\hijl\.conda\envs\seisbench\lib\site-packages\torch\utils\data\dataloader.py", line 1402, in _process_data
    data.reraise()
  File "C:\Users\hijl\.conda\envs\seisbench\lib\site-packages\torch\_utils.py", line 461, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "C:\Users\hijl\.conda\envs\seisbench\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\hijl\.conda\envs\seisbench\lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "C:\Users\hijl\.conda\envs\seisbench\lib\site-packages\torch\utils\data\_utils\collate.py", line 160, in default_collate
    return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
  File "C:\Users\hijl\.conda\envs\seisbench\lib\site-packages\torch\utils\data\_utils\collate.py", line 160, in <dictcomp>
    return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
  File "C:\Users\hijl\.conda\envs\seisbench\lib\site-packages\torch\utils\data\_utils\collate.py", line 149, in default_collate
    return default_collate([torch.as_tensor(b) for b in batch])
  File "C:\Users\hijl\.conda\envs\seisbench\lib\site-packages\torch\utils\data\_utils\collate.py", line 139, in default_collate
    storage = elem.storage()._new_shared(numel, device=elem.device)
  File "C:\Users\hijl\.conda\envs\seisbench\lib\site-packages\torch\storage.py", line 607, in _new_shared
    untyped_storage = torch._UntypedStorage._new_shared(size * self.element_size(), device=device)
  File "C:\Users\hijl\.conda\envs\seisbench\lib\site-packages\torch\storage.py", line 206, in _new_shared
    return cls._new_using_filename_cpu(size)
RuntimeError: Couldn't open shared file mapping: <000001BAF48D9002>, error code: <1455>

Epoch 0:  65%|██████▍   | 23042/35597 [2:09:13<1:10:24,  2.97it/s, loss=0.0265, v_num=8_7]
Could not load symbol cublasGetSmCountTarget from cublas64_11.dll. Error code 127

Process finished with exit code 1


And it also becomes longer in time. What is the reason for this? I have successfully used the GPU, I think it may be the reason for PL? There is no preloaded waveform in seisbench and the training is still very fast.

**Comment by yetinam** [comment]
Hi @Pengling2022 ,

thanks for the details. I'm not fully certain, this is still a memory error. Did you validate this, e.g., with your task manager? The key parameter to check is the `cache` [attribute of the dataset](https://seisbench.readthedocs.io/en/stable/pages/documentation/data.html#seisbench.data.base.WaveformDataset). If this is not None, over time, the whole dataset will be stored in memory over time. You might also want to reduce the number of data loaders to reduce the memory footprint.

As I'm not certain whether this is the same issue as the one originally presented here, I'd ask you to open a new issue should your problem persiste.
