### ISSUE TITLE
Possible cause of significant difference in download speed for metadata and dataset

### ISSUE THREAD

**Issue by suchanun** [seisbench/seisbench#301]
For metadata download, the speed on my machine was ~1.06MB/s. However, after the metadata was done downloading, the dataset's download speed dropped significantly to ~147kB/s. Are there any possible causes for this? or any recommendations? Thank you!

Also I tried to run the download in background but got 

> Traceback (most recent call last):
  File "<stdin>", line 10, in <module>
  File "/myenv/lib/python3.10/site-packages/seisbench/data/scedc.py", line 32, in __init__
    super().__init__(citation=citation, repository_lookup=True, **kwargs)
  File "/myenv/lib/python3.10/site-packages/seisbench/data/base.py", line 2162, in __init__
    super().__init__(path=None, name=self._name_internal(), chunks=chunks, **kwargs)
  File "/myenv/lib/python3.10/site-packages/seisbench/data/base.py", line 155, in __init__
    self._data_format = self._read_data_format()
  File "/myenv/lib/python3.10/site-packages/seisbench/data/base.py", line 643, in _read_data_format
    with h5py.File(waveform_file, "r") as f_wave:
  File "/myenv/lib/python3.10/site-packages/h5py/_hl/files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/myenv/lib/python3.10/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
OSError: Unable to synchronously open file (truncated file: eof = 1799045103, sblock->base_addr = 0, stored_eof = 683233432916)

**Comment by suchanun** [comment]
Thank you very much for your help!
