### ISSUE TITLE
List of pre-trained models

### ISSUE THREAD

**Issue by babulab** [seisbench/seisbench#95]
Hi,
I'm trying to load the pre-trained model CRED on Iquique database using: sbm.CRED.from_pretrained("iquique"). But this gives me this error

```
2022-06-06 16:11:16,537 | seisbench | WARNING | The download precheck failed with status code 404. This is not an error itself, but might indicate a subsequent error. If you encounter an error, this might be caused by the firewall setup of your network. Please check https://github.com/seisbench/seisbench#known-issues for details.
Traceback (most recent call last):
  File "/home/lptv/Aaron/Seisbench/Execute48.py", line 19, in <module>
    model = sbm.CRED.from_pretrained('iquique')
  File "/home/lptv/anaconda3/envs/seisbench/lib/python3.9/site-packages/seisbench/models/base.py", line 114, in from_pretrained
    seisbench.util.callback_if_uncached(
  File "/home/lptv/anaconda3/envs/seisbench/lib/python3.9/site-packages/seisbench/util/file.py", line 256, in callback_if_uncached
    callback(partial_files[0])
  File "/home/lptv/anaconda3/envs/seisbench/lib/python3.9/site-packages/seisbench/models/base.py", line 102, in download_weights_callback
    util.download_http(remote_weight_path, weight_path)
  File "/home/lptv/anaconda3/envs/seisbench/lib/python3.9/site-packages/seisbench/util/file.py", line 36, in download_http
    raise ValueError(
ValueError: Invalid URL. Request returned status code 404.
```

I saw that this problem is known https://github.com/seisbench/seisbench#known-issues . And I already verified that port 2443 is open, but the problem continues. Any idea how to solve this problem?

I'm not sure, but I think that CRED model trained with Iquique DB  is not among the pretrained models, I say this based on this: https://dcache-demo.desy.de:2443/Helmholtz/HelmholtzAI/SeisBench/models/cred/ 

Many thanks,
Marcelo M.

**Comment by babulab** [comment]
Thank you very much for the reply,
Ahh perfect, I understand.
Yes, we tested others models trained elsewhere on our data and it work pretty well

Thanks Jannes
